# 池化层
#### 实现池化层的正向传播

In [4]:
import torch
from torch import nn

def pool2d(X,pool_size,mode='max'):
    p_h,p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

#### 验证二维最大池化层的输出

In [5]:
x = torch.tensor([[0.0,1.0,2.0],
                 [3.0,4.0,5.0],
                 [6.0,7.0,8.0]])
pool2d(x,(2,2))

tensor([[4., 5.],
        [7., 8.]])

#### 验证平均池化层

In [7]:
pool2d(x,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

#### 填充和步幅

In [8]:
x = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [11]:
pool2d = nn.MaxPool2d(2)
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

#### 填充和步幅可以手动设定

In [14]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [15]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(x)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

#### 池化层在每个通道上单独运算

In [16]:
x = torch.cat((x,x+1),1)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [17]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])